name: tcm_backend CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/tcm_dev
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_URL: redis://localhost:6379

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tcm_dev
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t nest-api .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
  

      - name: Tag image
        run: docker tag nest-api ${{ secrets.DOCKER_USER }}/nest-api:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/nest-api:latest